language: java
jdk:
  - oraclejdk8

cache:
  directories:
  - $HOME/.gradle

script:
  - gradle

notifications:
  email:
    recipients:
      - avdayan@bgu.ac.il
      - avivmag@post.bgu.ac.il
      - dok@post.bgu.ac.il
    on_success: always
    on_failure: always
