language: java
jdk:
  - oraclejdk8

cache:
  directories:
  - $HOME/.gradle

script:
  - gradle

notifications:
  email:
    recipients:
      - avdayan@bgu.ac.il
      -avivmag@post.bgu.ac.ul
      -dok@post.bgu.ac.uk
    on_success: always
    on_failure: always
